### ISSUE TITLE
Second Part of Credit Website

### ISSUE THREAD

**Issue by zooqueen** [luxdefi/sites#18]
You can also look at the figma here [dev mode link] (https://www.figma.com/file/pVZ4hZqlR2g8Twne1LcDvx/Spectral-Gradient-Pack?type=design&node-id=98%3A2&mode=dev&t=Uqj6pW4pinhmXvi1-1)

The credit should be a carousel with all the cards still need to design 2 more and you can just crop these images so that its just the front for now

<img width="489" alt="Untitled 5" src="https://github.com/luxdefi/sites/assets/98129351/16ebec42-e478-4323-82c5-eab04334e0d6">

[figma](https://www.figma.com/file/pVZ4hZqlR2g8Twne1LcDvx/Spectral-Gradient-Pack?type=design&node-id=98%3A2&mode=design&t=Uqj6pW4pinhmXvi1-1)
![9](https://github.com/luxdefi/sites/assets/98129351/5c0c6915-dcba-41be-939a-65a2451de72c)
![rainbow chrome 2](https://github.com/luxdefi/sites/assets/98129351/d65b4c56-e487-4b2e-bc1e-d15e33fb976b)
![Untitled design (43)](https://github.com/luxdefi/sites/assets/98129351/501537ad-f9a5-476f-b992-4b53edfd430a)
![2](https://github.com/luxdefi/sites/assets/98129351/5571f922-5f2d-4f8c-a8bd-0a8ff5fa1807)

![1](https://github.com/luxdefi/sites/assets/98129351/608781cd-e02d-4ec7-a3f7-c2441ab554a1)

**Comment by erikrakuscek** [comment]
Card carousel done on credit site using the flat card images and an updated design.
