### ISSUE TITLE
Add Item to footer

### ISSUE THREAD

**Issue by zooqueen** [luxdefi/sites#31]
<img width="1601" alt="Untitled 2" src="https://github.com/luxdefi/sites/assets/98129351/f4b05851-4fea-4405-98ee-73e1f78e9fa5">

Where the red is we should put Launch Subnet that links here https://docs.lux.network/build/subnet/hello-subnet 

BECAUSE on avalanche site it is a key proponent and currently the only place you can see it now is if you actually have the docs.lux.market url which is hard to get to from main lux.network site

**Comment by artemis-prime** [comment]
Done in upcoming deploy of sites
