### ISSUE TITLE
checkout: mobile responsive view

### ISSUE THREAD

**Issue by zooqueen** [luxdefi/sites#58]
Heres the iphone mini/ tablet checkout

Still working on finishing up the rest https://www.figma.com/file/pVZ4hZqlR2g8Twne1LcDvx/lux-credit-website-flow?type=design&node-id=460-2148&mode=design

**Comment by zeekay** [comment]
![Screenshot 2024-03-18 at 3 47 31 PM](https://github.com/luxdefi/sites/assets/285707/289e8c06-bdb0-4bf0-bc0f-747b67ea4fe6)

Order summary should be collapsed by default on mobile, this is key issue missing.

**Comment by erikrakuscek** [comment]
Accordion to collapse the bag on checkout was added in https://github.com/hanzoai/react-sdk/pull/67
