### ISSUE TITLE
Get Desktop to match Figma

### ISSUE THREAD

**Issue by zooqueen** [luxdefi/sites#60]
Can we get the desktop home to match the figma as close as possible?

https://www.figma.com/file/pVZ4hZqlR2g8Twne1LcDvx/lux-credit-website-flow?type=design&node-id=98%3A2&mode=design&t=ClQSziE35YLg3E1T-1 

getting the flat cc models so we can put them in this page and use arrows to browse different card designs
<img width="410" alt="Untitled 5" src="https://github.com/luxdefi/sites/assets/98129351/c154128d-d570-4e7a-92f6-6d0ef4832acc">

Some of the written content is not right but I will revise all of it tomorrow, we need to make sure the spacing, margins, and text sizes look correct 

Please replace the single cards with the models if possible : )

**Comment by zeekay** [comment]
This should use the new carousel, which should fix most of issues

**Comment by erikrakuscek** [comment]
Used the updated cards carousel design from figma.
