### ISSUE TITLE
Fix Main Lux Credit Landing Page

### ISSUE THREAD

**Issue by zooqueen** [luxdefi/sites#65]
-Can we at least center the content 
-remove the 50% fine print content 
-replace the black card image with the 3D version 
-The word new should have "n" be Capitalized

<img width="1577" alt="Untitled 2" src="https://github.com/luxdefi/sites/assets/98129351/3700b5dd-f07e-41b0-bc0f-f8ab904e67f5">

fix the mobile landing page to look more like this 
<img width="304" alt="Untitled 2" src="https://github.com/luxdefi/sites/assets/98129351/4ea70bf9-a100-45e7-9729-46183455f987">

**Comment by erikrakuscek** [comment]
Still on TODO: "replace the black card image with the 3D version", everything else has been fixed. Druk font. Druk wide font does not support "%"
![image](https://github.com/luxdefi/sites/assets/17453589/2d4d3a33-ebf5-470e-9cf8-3a5fdd3a1bd7)
