### ISSUE TITLE
Landing page on lux.network

### ISSUE THREAD

**Issue by zooqueen** [luxdefi/sites#74]
Can we make sure all of the floating pyramids show? 
I also see the one on the top left is cropped. 

I also think it would look better if the buttons were 2 over 1. 

The two un-filled buttons together and then the white button at the span of both the buttons + their in between spacing, kind like the image below 

<img width="790" alt="Untitled 13" src="https://github.com/luxdefi/sites/assets/98129351/ef1ae406-5426-447a-9777-1ce342f3b2c5">

**Comment by zeekay** [comment]
It used to be one big button with the secondary on bottom, i think thats what we should do again.

**Comment by zeekay** [comment]
Lets also change these buttons to the most important things:

[ Run the Chain ] -> lux.market/validator buy flow
[ Learn More ] [ Open Source ] docs.lux.network, github respectively

**Comment by zeekay** [comment]
Lets also pull up the coin/validator buy cards as next thing after hero to drive it home and make sure they have buy links also

**Comment by van123helsing** [comment]
I made changes on `network/style-changes` branch.

The hero drive looks like this now:

![image](https://github.com/luxdefi/sites/assets/17568696/9fa252d2-0acc-47fc-9d3d-84c11eaa6d7e)

And the next slide is:

![image](https://github.com/luxdefi/sites/assets/17568696/a1148312-f251-4296-b311-fe454af83d41)

Where the buy links are:
https://lux.market/buy?sku=LXM-VL-GN
https://lux.market/buy?sku=LXM-CN-10B

Please take a look.

**Comment by zeekay** [comment]
Perfect, can you open a pull request so we can merge @van123helsing

**Comment by zeekay** [comment]
Make sure to note in the body of the pull request or commit "Closes #74"
