### ISSUE TITLE
checkout: bug from market not rendering overlay properly

### ISSUE THREAD

**Issue by zeekay** [luxdefi/sites#83]
For some reason when you click cart icon from lux.market it will not load the checkout view correctly on desktop (at least):

![Screenshot 2024-03-18 at 3 56 33 PM](https://github.com/luxdefi/sites/assets/285707/b479bcc9-0f41-4206-a59c-9ffde2fa0656)

**Comment by erikrakuscek** [comment]
This was fixed in https://github.com/hanzoai/react-sdk/pull/64
Checkout now displays properly full width on all sites
