### ISSUE TITLE
chat: Preserve new line when submitting message

### ISSUE THREAD

**Issue by zeekay** [luxdefi/sites#90]
Right now newlines seem to get stripped out when sending multiline messages, these are used to separate content / notions and it makes the LLM confused / breaks responses.

**Comment by aljosaRakita** [comment]
Already fixed on dev, just need to merge into prod.
![image](https://github.com/luxdefi/sites/assets/64634620/d78dd2cb-1ab5-483f-8004-73410eeb0d09)
